### ISSUE TITLE
Cant load slick-theme.css

### ISSUE THREAD

**Issue by romainquellec** [vercel/next-plugins#273]
I'm trying to load the slick-theme.css (https://github.com/kenwheeler/slick/blob/master/slick/slick-theme.css) but i'm getting : 

```
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type.
```

When I delete this part: 

```
@charset 'UTF-8';
/* Slider */
.slick-loading .slick-list
{
    background: #fff url('./ajax-loader.gif') center center no-repeat;
}

/* Icons */
@font-face
{
    font-family: 'slick';
    font-weight: normal;
    font-style: normal;

    src: url('./fonts/slick.eot');
    src: url('./fonts/slick.eot?#iefix') format('embedded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype'), url('./fonts/slick.svg#slick') format('svg');
}
```
everything is fine.

Related to this : https://github.com/webpack-contrib/mini-css-extract-plugin/issues/282

**Comment by needcaffeine** [comment]
I just successfully loaded this with next 7.0.0 and next-sass 1.0.1. Does that combo work for you? If not, can you show how you are importing the file?

**Comment by romainquellec** [comment]
I'm importing it like this on a page : 

```
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
```
I'm importing other css files in different pages with no problems.

**Comment by guigrpa** [comment]
Having the same issue trying to import the [typeface-raleway module](https://www.npmjs.com/package/typeface-raleway).

Example contents of this file:

```css
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-display: swap;
  font-weight: 100;
  src:
    local('Raleway Thin '),
    local('Raleway-Thin'),
    url('./files/raleway-latin-100.woff2') format('woff2'), /* Super Modern Browsers */
    url('./files/raleway-latin-100.woff') format('woff'); /* Modern Browsers */
}

/* raleway-100italic - latin */
@font-face {
  font-family: 'Raleway';
  font-style: italic;
  font-display: swap;
  font-weight: 100;
  src:
    local('Raleway Thin italic'),
    local('Raleway-Thinitalic'),
    url('./files/raleway-latin-100italic.woff2') format('woff2'), /* Super Modern Browsers */
    url('./files/raleway-latin-100italic.woff') format('woff'); /* Modern Browsers */
}
```
