### ISSUE TITLE
[next-css] loops/logic in css?

### ISSUE THREAD

**Issue by mastef** [vercel/next-plugins#593]
Sorry if this was covered under a different term. Is there a way to introduce logic into css files, such as loops?

For example I have a list of a lot of background image files ( 40+ ), which have different background image variations defined based on the browser capabilities and/or preload spacefillers : 
```css
.preload.section1 {
  background-image: url('../static/images/section1.jpg?lqip');
}
.webp .section1 {
  background-image: url('../static/images/section1.jpg?webp');
}
.no-webp .section1 {
  background-image: url('../static/images/section1.jpg');
}
```
And now I am planning on adding different sizes for each, so there's many lines that would basically have the same content, except the filename.

```css
.preload.section1 {
  background-image: url('../static/images/section1.jpg?lqip');
}
.webp .section1 {
  background-image: url('../static/images/section1.jpg?webp');
}
.no-webp .section1 {
  background-image: url('../static/images/section1.jpg');
}
@media (max-width:1280px) {
  .no-webp .section1 {
    background-image: url('../static/images/section1.jpg?resize&size=1280');
  }
}
@media (max-width:1024px) {
  .no-webp .section1 {
    background-image: url('../static/images/section1.jpg?resize&size=1024');
  }
}
@media (max-width:767px) {
  .no-webp .section1 {
    background-image: url('../static/images/section1.jpg?resize&size=768');
  }
}
@media (max-width:400px) {
  .no-webp .section1 {
    background-image: url('../static/images/section1.jpg?resize&size=400');
  }
}
```
For a list of 40+ pictures each.

Is there a way with next-css to create a loop within the .css file or am I taking the wrong approach here?
